


services:
  app:
    container_name: listaCompra-api
    env_file:
      - ./.env
    build: .
    volumes:
      - ./:/usr/src/mymaven:rw
    depends_on:
      - db
    ports:
      - '8080:8080'

  db:
    container_name: listaCompra-db
    image: postgres
    volumes:
      - listaCompra:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - '5432:5432'




volumes:
  listaCompra:
    external: true